### ISSUE TITLE
Crashes on latest Android Studio 2.1 with Android N preview

### ISSUE THREAD

**Issue by bootstraponline** [vpedak/droidtestrec#22]
I know webviews aren't supported but it'd be nice not to crash.

```
java.lang.AbstractMethodError: abstract method "android.view.View android.webkit.WebViewProvider$ViewDelegate.findFocus(android.view.View)"
at android.webkit.WebView.findFocus(WebView.java:2633)
at android.view.ViewGroup.findFocus(ViewGroup.java:1050)
at android.view.ViewGroup.findFocus(ViewGroup.java:1050)
at android.view.ViewGroup.findFocus(ViewGroup.java:1050)
at android.view.ViewGroup.findFocus(ViewGroup.java:1050)
at android.view.ViewGroup.findFocus(ViewGroup.java:1050)
at android.view.ViewGroup.findFocus(ViewGroup.java:1050)
at android.view.ViewGroup.findFocus(ViewGroup.java:1050)
at android.view.ViewGroup.findFocus(ViewGroup.java:1050)
at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3520)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:6066)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:770)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660)

Test running failed: Instrumentation run failed due to 'java.lang.AbstractMethodError'
```

**Comment by vpedak** [comment]
new version 0.9.5 with the fix was uploaded to plugins repository

@bootstraponline I was not able to fully reproduce this issue, so can you please verify that is is working at your side now if you will have time. Thanks.
