### ISSUE TITLE
Android studio throws NoSuchMethodError

### ISSUE THREAD

**Issue by rysh88** [vpedak/droidtestrec#27]
Hi I'm using Android Studio 2.1.1 on a Mac and I get this error as soon as when I hit the record button.

java.io.File.toPath()Ljava/nio/file/Path;
java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
    at com.vpedak.testsrecorder.plugin.actions.ToolsTestsRecorderAction.record(ToolsTestsRecorderAction.java:410)
    at com.vpedak.testsrecorder.plugin.actions.ToolsTestsRecorderAction.access$100(ToolsTestsRecorderAction.java:64)
    at com.vpedak.testsrecorder.plugin.actions.ToolsTestsRecorderAction$1.actionPerformed(ToolsTestsRecorderAction.java:123)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
    at java.awt.Component.processMouseEvent(Component.java:6414)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
    at java.awt.Component.processEvent(Component.java:6179)
    at java.awt.Container.processEvent(Container.java:2084)
    at java.awt.Component.dispatchEventImpl(Component.java:4776)
    at java.awt.Container.dispatchEventImpl(Container.java:2142)
    at java.awt.Component.dispatchEvent(Component.java:4604)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4279)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
    at java.awt.Container.dispatchEventImpl(Container.java:2128)
    at java.awt.Window.dispatchEventImpl(Window.java:2492)
    at java.awt.Component.dispatchEvent(Component.java:4604)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:690)
    at java.awt.EventQueue$3.run(EventQueue.java:688)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by vpedak** [comment]
It looks like you are using Java 6 to run Android Studio. Test Recorder is working only at Java 7 or higher.  Can you please switch to java 7? Here is details how to switch JDK for Android Stusio - http://tools.android.com/tech-docs/configuration/osx-jdk

**Comment by rysh88** [comment]
I still get the same error. I even tried updating JDK to the latest version.
Here's my setting,

![screen shot 2016-05-17 at 10 32 39 am](https://cloud.githubusercontent.com/assets/3083050/15327968/50c1d0de-1c21-11e6-9e42-bfb30ebd2ee2.png)

**Comment by vpedak** [comment]
You are talking about SDK that is used _inside_ Android Studio and I was talked about SDK that is used to _run_ Android Studio itself. Take a look please at section "IDE JDK" of the link http://tools.android.com/tech-docs/configuration/osx-jdk
