### ISSUE TITLE
ClassCastException with groovy class

### ISSUE THREAD

**Issue by Mistic92** [vpedak/droidtestrec#5]
It happens when I'm trying to record groovy class

```
2015-11-20 21:59:24,865 [ 428232]  ERROR - llij.ide.plugins.PluginManager - org.jetbrains.plugins.groovy.lang.psi.impl.GroovyFileImpl cannot be cast to com.intellij.psi.PsiJavaFile 
java.lang.ClassCastException: org.jetbrains.plugins.groovy.lang.psi.impl.GroovyFileImpl cannot be cast to com.intellij.psi.PsiJavaFile
    at com.vpedak.testsrecorder.plugin.actions.ToolsTestsRecorderAction.record(ToolsTestsRecorderAction.java:290)
    at com.vpedak.testsrecorder.plugin.actions.ToolsTestsRecorderAction.access$100(ToolsTestsRecorderAction.java:48)
    at com.vpedak.testsrecorder.plugin.actions.ToolsTestsRecorderAction$1.actionPerformed(ToolsTestsRecorderAction.java:104)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2015-11-20 21:59:24,867 [ 428234]  ERROR - llij.ide.plugins.PluginManager - Android Studio 1.5  Build #AI-141.2422023 
2015-11-20 21:59:24,867 [ 428234]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_60-ea 
2015-11-20 21:59:24,867 [ 428234]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
```

**Comment by vpedak** [comment]
I am sorry, but Groovy is not supported yet by this plugin. Maybe in future I will add Groovy support, but it is difficult to say when.
